### 1. ユーザー作成
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John",
  "nickname": "do"
}

### 2. ユーザー情報の書き換え
PUT http://localhost:3000/users
Content-Type: application/json

{
  "id": "clsn97pdu0000l9aeq1wha7az",
  "name": "ham"
}

### 3. ユーザー情報の取得
GET http://localhost:3000/users?id=clsn97pdu0000l9aeq1wha7az
Content-Type: application/json

### 4. ユーザー削除
DELETE http://localhost:3000/users/clsn97pdu0000l9aeq1wha7az
Content-Type: application/json
